name: localization_zone_gen
description: Flutter Localization made easy.
version: 0.0.1
homepage: https://github.com/DiveZone/LocalizationZone
repository: https://github.com/DiveZone/LocalizationZone
issue_tracker: https://github.com/DiveZone/LocalizationZone

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  localization_zone_annotations:
    path: ../localization_zone_annotations
  build: ">=1.3.0 <2.0.0"
  source_gen: ">=0.9.5 <1.0.0"
  yaml: '>=2.2.1 <3.0.0'

dev_dependencies:
  build_runner: ">=1.10.0 <2.0.0"
  build_test: ">=1.2.0 <2.0.0"
  test: ">=1.15.0 <2.0.0"  