name: localization_zone_example
version: 1.0.0
homepage: https://github.com/DiveZone/dzLang

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  localization_zone:
    path: ../localization_zone

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  localization_zone_gen:
    path: ../localization_zone_gen

flutter:
  uses-material-design: true

localization_zone:
  format: yaml
  input_path: locales
  output_path: lib/local
  locales: en, nl